package com.example.model

object HeroRegistry {
    val allHeroes: List<Hero> = listOf(
        Hero(
            id = "okcu_elf",
            name = "Okçu Elf",
            title = "Zümrüt Ormanı Nişancısı",
            role = HeroRole.RANGED,
            maxHp = 680,
            attack = 115,
            defense = 16,
            attackSpeedSeconds = 1.0f,
            attackRange = AttackRange.RANGED,
            skillName = "Ok Yağmuru",
            skillDesc = "Gökyüzüne fırlatılan oklar tüm düşman saflarına yağarak 180 hasar verir ve saldırı hızlarını 2.5 sn %25 yavaşlatır.",
            colorHex = 0xFF10B981,
            emoji = "🏹",
            lore = "Kadim ormanların koruyucusu. Yayından fırlayan her ok rüzgarın gücüyle hedefi asla şaşmaz."
        ),
        Hero(
            id = "siyah_ork",
            name = "Siyah Ork",
            title = "Karanlık Dağlar Reisi",
            role = HeroRole.WARRIOR,
            maxHp = 1250,
            attack = 130,
            defense = 32,
            attackSpeedSeconds = 1.3f,
            attackRange = AttackRange.MELEE,
            skillName = "Ork Gazabı & Kükreme",
            skillDesc = "Vahşi bir kükremeyle öndeki düşmana 270 ezici hasar vurur ve verilen hasarın %45'i kadar kendi canını yeniler.",
            colorHex = 0xFFDC2626,
            emoji = "👹",
            lore = "Savaş yaralarıyla dolu zırhı ve dev baltasıyla düşman saflarını yaran durdurulamaz bir güç."
        ),
        Hero(
            id = "zirhli_insan",
            name = "Zırhlı İnsan",
            title = "Kraliyet Başşövalyesi",
            role = HeroRole.WARRIOR,
            maxHp = 1150,
            attack = 100,
            defense = 48,
            attackSpeedSeconds = 1.2f,
            attackRange = AttackRange.MELEE,
            skillName = "Kutsal Kılıç Darbesi",
            skillDesc = "Kutsanmış kılıcıyla hedefe 230 kutsal hasar indirir ve hedefin zırhını 4 saniyeliğine 25 puan kırar.",
            colorHex = 0xFFF59E0B,
            emoji = "⚔️",
            lore = "Kralına ve krallığına sadakat yemini etmiş, çelikten zırhı ve adaleti temsil eden şövalye."
        ),
        Hero(
            id = "muhafiz",
            name = "Muhafız",
            title = "Aegis Kalkanı Koruyucusu",
            role = HeroRole.TANK,
            maxHp = 1400,
            attack = 72,
            defense = 58,
            attackSpeedSeconds = 1.5f,
            attackRange = AttackRange.MELEE,
            skillName = "Aegis Kalkan Duvarı",
            skillDesc = "Bütün takım arkadaşlarına 260 puanlık hasar emen koruyucu kalkan açar ve 3 saniye düşman saldırılarını kendi üstüne çeker.",
            colorHex = 0xFF3B82F6,
            emoji = "🛡️",
            lore = "Koca kalkanının arkasında duran hiçbir müttefik kolay kolay yere düşmez."
        ),
        Hero(
            id = "robot_tank",
            name = "Robot Tank",
            title = "Siber Muharebe Mk-IV",
            role = HeroRole.TANK,
            maxHp = 1550,
            attack = 88,
            defense = 52,
            attackSpeedSeconds = 1.6f,
            attackRange = AttackRange.RANGED,
            skillName = "Roket Yaylımı",
            skillDesc = "Omuz bataryalarından güdümlü 3 roket fırlatır; düşman ön saflarına 300 patlayıcı hasar verir ve yanma başlatır.",
            colorHex = 0xFF06B6D4,
            emoji = "🤖",
            lore = "Gelişmiş alaşımlar ve reaktör teknolojisiyle donatılmış, yıkıcı roket podlarına sahip savaş makinesi."
        ),
        Hero(
            id = "tas_golemi",
            name = "Taş Golemi",
            title = "Kadim Zirve Devi",
            role = HeroRole.TANK,
            maxHp = 1750,
            attack = 65,
            defense = 65,
            attackSpeedSeconds = 1.8f,
            attackRange = AttackRange.MELEE,
            skillName = "Sismik Deprem",
            skillDesc = "Yere devasa bir yumruk vurarak tüm düşmanları sarsar (150 hasar) ve öndeki iki düşmanı 2 saniye sersemletir.",
            colorHex = 0xFF78716C,
            emoji = "🗿",
            lore = "Yüzyıllar boyunca dağların derinliğinde uyuyan, devasa granit kayalardan oluşmuş yıkılmaz bir varlık."
        ),
        Hero(
            id = "alev_buyucusu",
            name = "Alev Büyücüsü",
            title = "Lav Vadisi Kıyamet Büyücüsü",
            role = HeroRole.MAGE,
            maxHp = 630,
            attack = 135,
            defense = 12,
            attackSpeedSeconds = 1.3f,
            attackRange = AttackRange.RANGED,
            skillName = "Kıyamet Ateşi",
            skillDesc = "En yüksek cana sahip düşmanın üstüne devasa alev patlaması indirir: 330 büyü hasarı ve 3 sn boyunca saniyede 35 yanma hasarı.",
            colorHex = 0xFFF97316,
            emoji = "🔥",
            lore = "Alevlerin dilini konuşan, baktığı her yeri kül etme kudretine sahip korkusuz bir büyücü."
        ),
        Hero(
            id = "golge_suikastci",
            name = "Gölge Suikastçı",
            title = "Gece Bıçakları Lideri",
            role = HeroRole.ASSASSIN,
            maxHp = 720,
            attack = 145,
            defense = 18,
            attackSpeedSeconds = 0.9f,
            attackRange = AttackRange.MELEE,
            skillName = "Gölge Arkası Suikast",
            skillDesc = "Düşmanın en arka hattındaki en kırılgan kahramanın arkasına anında sıçrayarak %250 kritik hasar (360+) vurur.",
            colorHex = 0xFF8B5CF6,
            emoji = "🗡️",
            lore = "Gölgeler arasında kaybolup düşman büyücü ve okçularını göz açıp kapayıncaya dek avlar."
        ),
        Hero(
            id = "sifaci_peri",
            name = "Şifacı Peri",
            title = "Işık Çeşmesi Muhafızı",
            role = HeroRole.SUPPORT,
            maxHp = 700,
            attack = 62,
            defense = 20,
            attackSpeedSeconds = 1.2f,
            attackRange = AttackRange.RANGED,
            skillName = "Hayat Baharı",
            skillDesc = "En yaralı 2 takım arkadaşına anında 290 can kazandırır ve tüm takıma 3 saniye boyunca yenilenme bahşeder.",
            colorHex = 0xFF14B8A6,
            emoji = "🧚",
            lore = "Saf ışıkla parıldayan kanatlarıyla savaş alanında dolaşarak müttefiklerinin yaralarını iyileştirir."
        ),
        Hero(
            id = "buz_cadisi",
            name = "Buz Cadısı",
            title = "Kuzey Ayazı Hükümdarı",
            role = HeroRole.MAGE,
            maxHp = 660,
            attack = 110,
            defense = 15,
            attackSpeedSeconds = 1.2f,
            attackRange = AttackRange.RANGED,
            skillName = "Buzul Fırtınası",
            skillDesc = "Düşman saflarına dondurucu tipi estirir; tüm düşmanlara 170 hasar vurur ve 2.5 saniyeliğine onları kısmen dondurur.",
            colorHex = 0xFF0284C7,
            emoji = "❄️",
            lore = "Sonsuz kışın dondurucu rüzgarlarını yöneten, buz kristalleriyle düşmanlarını felç eden kadim cadı."
        )
    )

    fun getHeroById(id: String): Hero {
        return allHeroes.firstOrNull { it.id == id } ?: allHeroes.first()
    }
}
